# Site settings
author: Justin Hall
title: justindhall
header-img: img/home-bg.png
email: hall.justin.d@gmail.com
copyright_name: Justin Hall
description: > # this means to ignore newlines until "baseurl:"
  i write lines
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  justindhall

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
